spring:
  application:
    name: spring-boot-java-25-scaffolding

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_java_25
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

app:
  jwt:
    secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1mb3ItZmxvd3l4LWRldi1vbmx5LTI1NmJpdHM=}
    expiration-ms: 900000
  refresh-token:
    expiration-days: 30
  google:
    client-id: 782368385632-mu9tpj6pi8mhrk0c55i9ekmouv8udbse.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/api/v1/auth/callback/google
    token-endpoint: https://oauth2.googleapis.com/token
    userinfo-endpoint: https://www.googleapis.com/oauth2/v2/userinfo
    auth-endpoint: https://accounts.google.com/o/oauth2/v2/auth
  cors:
    allowed-origins: http://localhost:5173
